import enum

from .device import (
    STATE_OPTIONITEM_ON,
    STATE_OPTIONITEM_OFF,
    STATE_OPTIONITEM_UNKNOWN,
    OPTIONITEMMODES,
    UNITTEMPMODES,
    STATE_UNKNOWN,
)


# Refrigerator Smart Saving
class STATE_REFR_SMARTSAV(enum.Enum):
    OFF = "Smart Saving Off"
    NIGHT_ON = "Smart Saving Night Mode On"
    CUSTOM_ON = "Smart Saving Custom Mode On"
    SMARTGRID_DR_ON = "Smart Grid Demand Response Mode On"
    SMARTGRID_DD_ON = "Smart Grid Delay Defrost Mode On"


# Refrigerator IcePlus
class STATE_REFR_ICEPLUS(enum.Enum):
    OFF = STATE_OPTIONITEM_OFF
    ON = STATE_OPTIONITEM_ON
    ICE_PLUS = "Ice Plus"
    ICE_PLUS_FREEZE = "Ice Plus Freeze"
    ICE_PLUS_OFF = "Ice Plus Off"


# Refrigerator Air Filter
class STATE_REFR_AIRFILTER(enum.Enum):
    OFF = STATE_OPTIONITEM_OFF
    AUTO = "Mode Auto"
    POWER = "Mode Power"
    REPLACE_FILTER = "Replace Filter"
    SMARTCARE_ON = "Smart Care On"
    SMARTCARE_OFF = "Smart Care Off"
    SMARTCARE_WAIT = "Smart Care Wait"


"""------------------for Refrigerator"""

REFRTEMPUNIT = {
    STATE_OPTIONITEM_UNKNOWN: STATE_UNKNOWN.UNKNOWN,
    "Ｆ": UNITTEMPMODES.Fahrenheit,
    "℃": UNITTEMPMODES.Celsius,
    "˚F": UNITTEMPMODES.Fahrenheit,
    "˚C": UNITTEMPMODES.Celsius,
}

REFRDOORSTATUS = {
    STATE_OPTIONITEM_UNKNOWN: STATE_UNKNOWN.UNKNOWN,
    "CLOSE": OPTIONITEMMODES.OFF,
    "OPEN": OPTIONITEMMODES.ON,
    "IGNORE": OPTIONITEMMODES.OFF,
}

REFRSMARTSAVMODE = {
    "@CP_OFF_EN_W": STATE_REFR_SMARTSAV.OFF,
    "@CP_TERM_USE_NOT_W": STATE_REFR_SMARTSAV.OFF,
    "@RE_SMARTSAVING_MODE_NIGHT_W": STATE_REFR_SMARTSAV.NIGHT_ON,
    "@RE_SMARTSAVING_MODE_CUSTOM_W": STATE_REFR_SMARTSAV.CUSTOM_ON,
    "@RE_TERM_DEMAND_RESPONSE_FUNCTIONALITY_W": STATE_REFR_SMARTSAV.SMARTGRID_DR_ON,
    "@RE_TERM_DELAY_DEFROST_CAPABILITY_W": STATE_REFR_SMARTSAV.SMARTGRID_DD_ON,
    "IGNORE": OPTIONITEMMODES.OFF,
}

REFRSMARTSAVSTATUS = {
    STATE_OPTIONITEM_UNKNOWN: STATE_UNKNOWN.UNKNOWN,
    "OFF": OPTIONITEMMODES.OFF,
    "ON": OPTIONITEMMODES.ON,
    "@CP_OFF_EN_W": OPTIONITEMMODES.OFF,
    "@CP_ON_EN_W": OPTIONITEMMODES.ON,
    "IGNORE": OPTIONITEMMODES.OFF,
}

REFRECOSTATUS = {
    STATE_OPTIONITEM_UNKNOWN: STATE_UNKNOWN.UNKNOWN,
    "@CP_OFF_EN_W": OPTIONITEMMODES.OFF,
    "@CP_ON_EN_W": OPTIONITEMMODES.ON,
    "IGNORE": OPTIONITEMMODES.OFF,
}

REFRICEPLUS = {
    "@CP_OFF_EN_W": STATE_REFR_ICEPLUS.OFF,
    "@CP_ON_EN_W": STATE_REFR_ICEPLUS.ON,
    "@RE_TERM_ICE_PLUS_W": STATE_REFR_ICEPLUS.ICE_PLUS,
    "@RE_MAIN_SPEED_FREEZE_TERM_W": STATE_REFR_ICEPLUS.ICE_PLUS_FREEZE,
    "@CP_TERM_OFF_KO_W": STATE_REFR_ICEPLUS.ICE_PLUS_OFF,
}

REFRAIRFILTER = {
    "@CP_TERM_OFF_KO_W": STATE_REFR_AIRFILTER.OFF,
    "@RE_STATE_FRESH_AIR_FILTER_MODE_AUTO_W": STATE_REFR_AIRFILTER.AUTO,
    "@RE_STATE_FRESH_AIR_FILTER_MODE_POWER_W": STATE_REFR_AIRFILTER.POWER,
    "@RE_STATE_REPLACE_FILTER_W": STATE_REFR_AIRFILTER.REPLACE_FILTER,
    "@RE_STATE_SMART_SMART_CARE_ON": STATE_REFR_AIRFILTER.SMARTCARE_ON,
    "@RE_STATE_SMART_SMART_CARE_OFF": STATE_REFR_AIRFILTER.SMARTCARE_OFF,
    "@RE_STATE_SMART_SMART_CARE_WAIT": STATE_REFR_AIRFILTER.SMARTCARE_WAIT,
}

REFRLOCKSTATUS = {
    STATE_OPTIONITEM_UNKNOWN: STATE_UNKNOWN.UNKNOWN,
    "UNLOCK": OPTIONITEMMODES.OFF,
    "LOCK": OPTIONITEMMODES.ON,
}

