import enum

from .device import (
    STATE_OPTIONITEM_ON,
    STATE_OPTIONITEM_OFF,
    STATE_OPTIONITEM_UNKNOWN,
    OPTIONITEMMODES,
    UNITTEMPMODES,
    STATE_UNKNOWN,
)


# Refrigerator IcePlus
class STATE_REFR_ICEPLUS(enum.Enum):
    OFF = STATE_OPTIONITEM_OFF
    ON = STATE_OPTIONITEM_ON
    ICE_PLUS = "Ice Plus"
    ICE_PLUS_FREEZE = "Ice Plus Freeze"
    ICE_PLUS_OFF = "Ice Plus Off"


# Refrigerator Air Filter
class STATE_REFR_AIRFILTER(enum.Enum):
    OFF = STATE_OPTIONITEM_OFF
    AUTO = "Mode Auto"
    POWER = "Mode Power"
    REPLACE_FILTER = "Replace Filter"
    SMARTCARE_ON = "Smart Care On"
    SMARTCARE_OFF = "Smart Care Off"
    SMARTCARE_WAIT = "Smart Care Wait"


# Refrigerator Smart Saving
class STATE_REFR_SMARTSAV(enum.Enum):
    OFF = STATE_OPTIONITEM_OFF
    NIGHT = "Night"
    CUSTOM = "Custom"


"""------------------for Refrigerator"""

REFRTEMPUNIT = {
    STATE_OPTIONITEM_UNKNOWN: STATE_UNKNOWN.UNKNOWN,
    "Ｆ": UNITTEMPMODES.Fahrenheit,
    "℃": UNITTEMPMODES.Celsius,
}

REFRICEPLUS = {
    "@CP_OFF_EN_W": STATE_REFR_ICEPLUS.OFF,
    "@CP_ON_EN_W": STATE_REFR_ICEPLUS.ON,
    "@RE_TERM_ICE_PLUS_W": STATE_REFR_ICEPLUS.ICE_PLUS,
    "@RE_MAIN_SPEED_FREEZE_TERM_W": STATE_REFR_ICEPLUS.ICE_PLUS_FREEZE,
    "@CP_TERM_OFF_KO_W": STATE_REFR_ICEPLUS.ICE_PLUS_OFF,
}

REFRAIRFILTER = {
    "@CP_TERM_OFF_KO_W": STATE_REFR_AIRFILTER.OFF,
    "@RE_STATE_FRESH_AIR_FILTER_MODE_AUTO_W": STATE_REFR_AIRFILTER.AUTO,
    "@RE_STATE_FRESH_AIR_FILTER_MODE_POWER_W": STATE_REFR_AIRFILTER.POWER,
    "@RE_STATE_REPLACE_FILTER_W": STATE_REFR_AIRFILTER.REPLACE_FILTER,
    "@RE_STATE_SMART_SMART_CARE_ON": STATE_REFR_AIRFILTER.SMARTCARE_ON,
    "@RE_STATE_SMART_SMART_CARE_OFF": STATE_REFR_AIRFILTER.SMARTCARE_OFF,
    "@RE_STATE_SMART_SMART_CARE_WAIT": STATE_REFR_AIRFILTER.SMARTCARE_WAIT,
}

REFRSMARTSAVMODE = {
    "@CP_TERM_USE_NOT_W": STATE_REFR_SMARTSAV.OFF,
    "@RE_SMARTSAVING_MODE_NIGHT_W": STATE_REFR_SMARTSAV.NIGHT,
    "@RE_SMARTSAVING_MODE_CUSTOM_W": STATE_REFR_SMARTSAV.CUSTOM,
}

REFRSMARTSAVSTATUS = {
    STATE_OPTIONITEM_UNKNOWN: STATE_UNKNOWN.UNKNOWN,
    "OFF": OPTIONITEMMODES.OFF,
    "ON": OPTIONITEMMODES.ON,
}

REFRDOORSTATUS = {
    STATE_OPTIONITEM_UNKNOWN: STATE_UNKNOWN.UNKNOWN,
    "CLOSE": OPTIONITEMMODES.OFF,
    "OPEN": OPTIONITEMMODES.ON,
}

REFRLOCKSTATUS = {
    STATE_OPTIONITEM_UNKNOWN: STATE_UNKNOWN.UNKNOWN,
    "UNLOCK": OPTIONITEMMODES.OFF,
    "LOCK": OPTIONITEMMODES.ON,
}

REFRECOSTATUS = {
    STATE_OPTIONITEM_UNKNOWN: STATE_UNKNOWN.UNKNOWN,
    "@CP_OFF_EN_W": OPTIONITEMMODES.OFF,
    "@CP_ON_EN_W": OPTIONITEMMODES.ON,
}

